FROM node:18
ENV TZ=Asia/Kolkata

RUN mkdir /usr/src/server
WORKDIR /usr/src/server

EXPOSE 7000

COPY package.json package-lock.json ./
COPY dist/ ./dist
COPY protos ./protos

RUN npm i --production --silent

ENTRYPOINT [ "node", "dist/main.js" ]



